spring:
  application:
    name: lovable-clone

  datasource:
    url: jdbc:postgresql://localhost:9010/pgvector-test
    username: DB_USERNAME
    password: DB_PASSWORD
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC

ai:
  openai:
    api-key:
    base-url: https://openrouter.ai/api
    chat:
      options:
        model: nvidia/nemotron-3-super-120b-a12b:free
        temperature: 0.0
jwt:
   secret-key: JWT_SECRET_KEY

stripe:
   api:
     secret-key: STRIPE_SECRET_KEY
   webhook:
     secret: STRIPE_WEBHOOK_SECRET

client.url: http://localhost:8080


logging:
  level:
    org.springframework.ai:
      chat.client: DEBUG

minio:
  url: http://localhost:9000
  access-key: MINIO_ACCESS_KEY
  secret-key: MINIO_SECRET_KEY
  project-bucket: projects